# Generated by Django 5.2.1 on 2025-07-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='overall_grade',
        ),
    ]
