# Generated by Django 5.2.1 on 2025-07-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_remove_grade_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My School', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
            ],
            options={
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
